Glottolog needs bs4
..or running anything fails with:

```
ModuleNotFoundError: No module named 'bs4'
```

Note that bs4 is only used in two lines of code and it might be easier to inline the import within the specific functions to raise when they're run, rather than adding a 150kb dependency for two minor(?) commands.